### ISSUE TITLE
Add ability to show WMS layer in the background (OpenLayers maybe?) If possible.

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/ca-crop-economics#10]
See https://gist.github.com/mbertrand/5218300 for example of combining OpenLayers and D3

**Comment by lilawren** [comment]
I'm going to try out leaflet http://bost.ocks.org/mike/leaflet/

I looked up examples of d3 + openlayers and I can't seem to find any working live examples because they used the older version which is deprecated.

**Comment by nickrsan** [comment]
Gotcha - if Mike Bostock says use leaflet with D3, then that sounds like
the route to go! Thanks Lawrence!

-Nick nick@enviroconsumer.org

**Comment by qjhart** [comment]
@jrmerz, do you have any additional wisdom to impart?  SVG vs Canvas possibly?

**Comment by jrmerz** [comment]
What is the issue, leaflet+WMS Background layer or leaflet+D3?

**Comment by lilawren** [comment]
I got leaflet + d3 to work.
